version: '3.1'

services:
  mongo:
    image: mongo:4.4.4-bionic
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}

  node:
    image: node:14.17
    working_dir: /var/app/
    command: npm start
    volumes:
      - node_modules:/var/app/src/node_modules
      - ./:/var/app/
    environment:
      NODE_OPTIONS: --experimental-vm-modules # needed for jest to work with ESM
      MONGO_DB_NAME: ${MONGO_DB_NAME-discordia}
      MONGO_PATH: mongodb://mongo:27017
    depends_on:
      - mongo

volumes:
  mongodb:
    driver: local
  node_modules:
    driver: local
