name: Linter

on:
    push:
        branches:
            - '**'
        tags-ignore:
            - 'v[0-9]+.[0-9]+.[0-9]+' # We don't want this to run on pushed release tags again

jobs:
    linter:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 1

            - uses: actions/setup-node@v1
              with:
                  node-version: '14.17.x'

            - uses: actions/cache@v2
              id: cache
              with:
                  path: node_modules
                  key: ${{ runner.os }}-npm-packages-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm install

            - name: Lint JS
              run: npm run lint:js
