name: Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+' # We don't want this to run on pushed release tags again

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:4.4.4-bionic
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: SAMPLE_USERNAME
          MONGO_INITDB_ROOT_PASSWORD: SAMPLE_PASSWORD
          MONGO_INITDB_DATABASE: discordia_tests

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v1
        with:
          node-version: '14.17.x'

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Execute Tests
        env:
          MONGO_PATH: mongodb://localhost:27017
          MONGO_DB_NAME: discordia_tests
          MONGO_USER: SAMPLE_USERNAME
          MONGO_PASSWORD: SAMPLE_PASSWORD
          COMMAND_PREFIX: '!'
        run: NODE_OPTIONS=--experimental-vm-modules npm run test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
            file: ./coverage/coverage-final.json
            name: jest unittests
            fail_ci_if_error: true
